### PR TITLE
doc(Deployment): Update guides for how to deploy.

### PR DESCRIPTION
**Pull request by ZL-Asica**
1. Add an explanation for what is `NUXT_SITE_TOKEN`.
2. Rename the page from `Settings` -> `Functions` to `Settings` -> `Bindings` -> `Add` since Cloudflare updated their page.
3. Add a guide for how to create a new `KV` before binding.
4. Add detailed guides for how to enable `Analytics Engine` and how to bind that to the pages.

主要更新点是Cloudflare更新的前端UI，名字都变了，不改一下文档的话新用户可能会比较懵。尤其是Analytics Engine这部分。

### CODE REVIEW

**Comment by ZL-Asica** [comment]
@ccbikai

**Comment by ZL-Asica** [comment]
link to issue #61

**Comment by ccbikai** [comment]
The KV in the image `docs/images/faqs-Analytics_engine.png` is not blurred. Do you mind? If it's not a problem, I can merge it directly.

**Comment by ZL-Asica** [comment]
Fixed. Please emerge.

**Pull request merged**
