### PR TITLE
feat: add case sensitivity configuration for slugs

### PR DESCRIPTION
**Pull request by ZL-Asica**
### PR Description:

This pull request introduces a new configuration to toggle case sensitivity for slugs in the Sink application. By default, slugs are case-insensitive for better usability, but users can now enable case-sensitive behavior via the `NUXT_CASE_SENSITIVE` environment variable. 

#### Key Changes:
1. **Feature: Case Sensitivity Configuration**
   - Added the `caseSensitive` option in `runtimeConfig` (default: `false`).
   - Slugs are automatically converted to lowercase unless `caseSensitive` is set to `true`.

2. **Updated Random Slug Generation**
   - Randomly generated slugs include both uppercase and lowercase letters when case sensitivity is enabled, significantly increasing the pool of unique slugs.

3. **Redirect Middleware Updates**
   - Middleware now respects the `caseSensitive` setting, treating slugs as case-sensitive if enabled.

4. **ESLint Config Fix**
   - Fixed a deprecated key in `.vscode/settings.json` (`eslint.experimental.useFlatConfig` → `eslint.useFlatConfig`) (for eslint v9+ no need to add that experimental)

5. **Documentation Updates**
   - Updated the FAQ and `README.md` to reflect the new feature.

### CODE REVIEW

**Comment by ZL-Asica** [comment]
This PR addresses issue #52 .

**Comment by ZL-Asica** [comment]
突然想到这个最好加一个` BREAKING CHANGE` 吧？

如果有用户之前用了大写的 key，在 sync 了最新的更改以后就会出问题（因为 KV 里存的是有大小写的，在`server/middleware/1.redirect.ts`这里我新增了根据 `caseSensitive` 去对 slug 进行了 `toLowerCase()` 的转换。

需要提醒这部分用户把 `env` 中的 `NUXT_CASE_SENSITIVE` 设置为 `true`

**Comment by ZL-Asica** [comment]
> 如果有用户之前用了大写的 key

应该不会很多，之前随机的 `slug` 只会生成小写字母

**Comment by ZL-Asica** [comment]
> 如果未读取到，再转换大小写去降级读取

加上了，逻辑是检测原始的，如果没有并且 casesensitive 是 false 我们再去检测小写。

**Comment by ccbikai** [comment]
components/dashboard/links/Editor.vue 中的转换是走不到的，我移除了。

这样可以向前保持一致了

**Pull request merged**
